### ISSUE TITLE
Socket onClose event doesn't fire on connected device

### ISSUE THREAD

**Issue by micahbule** [Rapsssito/react-native-tcp-socket#16] opened 2020-01-10 09:40 UTC
## Description
`close` event for either client nor server doesn't fire when the other device disconnects.

## Steps to reproduce
1. Instantiate a TcpServer on device1 and register an event listener to the `close` event of the connecting `socket`.
2. Create a TcpClient on device2, connect it to device1, and register an event listener to the `close` event of the client socket.
3. Call `.close()` on either the socket connected to the TcpServer, or the one created by the TcpClient.
 
## Current behavior
If you call `.close()` on the socket connected to the TcpServer, only the event listener on the TcpServer will fire, not the one if the TcpClient. Vice versa.

## Expected behavior
Calling `.close()` on the socket will fire both the `close` event listeners registered on the server and client.

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android   |
| react-native | 0.61.4   |
| react-native-tcp-socket  | 3.1.2   |

**Comment by Rapsssito** [comment] 2020-01-10 09:47
@micahbule, thanks for the issue! Working on it!

**Comment by Rapsssito** [comment] 2020-01-10 10:58
@micahbule, is this also reproducible in iOS?

**Comment by micahbule** [comment] 2020-01-10 11:31
@Rapsssito I haven't tried it on iOS as I don't have a device to try it with.

**Comment by Rapsssito** [comment] 2020-01-10 11:32
I will release an Android fix since I don't have enough time to debug iOS right now.

**Comment by micahbule** [comment] 2020-01-10 11:35
Sure thing. I'll try to reproduce it on iOS if I have time. Thanks so much!

**Comment by Rapsssito** [comment] 2020-01-10 15:29
**Should be fixed in [3.1.3](https://github.com/Rapsssito/react-native-tcp-socket/commit/464bdcd6f1094b5033d7ae8738c684636e6dcaa9).** Feel free to reopen this issue if the problem persists.

**Closed by Rapsssito** 2020-01-10 15:29 UTC
Labels: bug
