### ISSUE TITLE
> Task :react-native-tcp-socket:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by houzhanshan** [Rapsssito/react-native-tcp-socket#59] opened 2020-06-24 08:49 UTC
> Task :react-native-tcp-socket:compileDebugJavaWithJavac FAILED
195 actionable tasks: 10 executed, 185 up-to-date
/../../../node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:74: 错误: 找不到符号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
/../../../node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:102: 错误: 找不到符号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
/../../../react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:128: 错误: 找不到符号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
/../../../node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:151: 错误: 找不到符号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
4 个错误

FAILURE: Build failed with an exception.

The above problem, how do I solve it, please help and give pointers, thank you !

**Comment by houzhanshan** [comment] 2020-06-24 08:50
"react-native": "0.60.5",

**Comment by Rapsssito** [comment] 2020-06-25 15:03
@houzhanshan, The issue is related to your RN version. The library uses methods only available in RN >= 0.61.

I have released **`1.2.2`**, compatible with RN 0.60. Check if everything works. Check the [README](https://github.com/Rapsssito/react-native-tcp-socket#react-native-compatibility) for more details.

Duplicate of #4

**Closed** 2020-06-25 15:03 UTC
Labels: bug, duplicate
